#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  8 14:07:58 2019

@author: ModiMacMod
"""

import pandas as pd

import sqlite3
conn=sqlite3.connect("twitter.db")   
       
hashTagsDF = pd.read_sql_query("select * from hashtags;", conn)
tweetsDF = pd.read_sql_query("select * from tweets;", conn)
conn.close()
